services:
  app:
    image: live_chat
    build: .
    env_file: ./.env
    container_name: live_chat
    hostname: live_chat
    depends_on:
      - pg
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    ports:
      - "127.0.0.1:3004:3000"
      - "172.17.0.1:3004:3000"
    networks:
      net:
    restart: always

  solid_queue:
    image: live_chat
    build: .
    env_file: ./.env
    container_name: live_chat_solid_queue
    hostname: live_chat_solid_queue
    depends_on:
      - pg
    command: ['bundle', 'exec', 'rails', 'solid_queue:start']
    networks:
      - net
    restart: unless-stopped

  pg:
    image: postgres:16.11
    container_name: live_chat_pg
    hostname: live_chat_pg
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Moscow
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - net
    restart: unless-stopped

volumes:
  db_data:

networks:
  net:
